window.businessData = {
  "businesses": [
    {
      "id": "1",
      "name": "Soul n Body",
      "category": "Health & Beauty",
      "description": "Halal skincare prophetic oils hijama therapy",
      "location": "London",
      "contact": "Email via website / Instagram DM",
      "source": "Instagram Website",
      "website": "",
      "instagram": ""
    },
    {
      "id": "2",
      "name": "Nurify Skin",
      "category": "Health & Beauty",
      "description": "Handmade halal skincare prophetic oils",
      "location": "London",
      "contact": "Instagram DM",
      "source": "Instagram Etsy",
      "website": "",
      "instagram": ""
    },
    {
      "id": "3",
      "name": "Sunnah Skincare UK",
      "category": "Health & Beauty",
      "description": "Prophetic skincare black seed products",
      "location": "East London",
      "contact": "Instagram DM",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "4",
      "name": "Glow by Saff",
      "category": "Health & Beauty",
      "description": "Natural serums Muslim-owned skincare",
      "location": "London",
      "contact": "Instagram DM",
      "source": "Instagram TikTok",
      "website": "",
      "instagram": ""
    },
    {
      "id": "5",
      "name": "Sakeenah Beauty",
      "category": "Health & Beauty",
      "description": "Halal skincare gentle cleansers",
      "location": "London",
      "contact": "Email via Instagram bio",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "6",
      "name": "Sampure Minerals",
      "category": "Health & Beauty",
      "description": "Halal-certified mineral makeup",
      "location": "London",
      "contact": "Customer service email",
      "source": "Website Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "7",
      "name": "Amara Halal Cosmetics",
      "category": "Health & Beauty",
      "description": "Halal makeup wudu-friendly",
      "location": "London stockists",
      "contact": "Email via website",
      "source": "Website Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "8",
      "name": "Haya Cosmetics UK",
      "category": "Health & Beauty",
      "description": "Halal lipsticks modest beauty",
      "location": "London",
      "contact": "Instagram DM",
      "source": "Instagram TikTok",
      "website": "",
      "instagram": ""
    },
    {
      "id": "9",
      "name": "D’Amani Spa & Salon",
      "category": "Health & Beauty",
      "description": "Women-only hijama massage halal spa",
      "location": "London",
      "contact": "Phone number on website",
      "source": "Instagram Website",
      "website": "",
      "instagram": ""
    },
    {
      "id": "10",
      "name": "Ayma Therapeutics",
      "category": "Health & Beauty",
      "description": "Women-only massage",
      "location": "London",
      "contact": "Instagram DM",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "11",
      "name": "Hijabista Hair",
      "category": "Health & Beauty",
      "description": "Women-only halal hair salon",
      "location": "London",
      "contact": "Phone number on Instagram",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "12",
      "name": "Beauty Kulture",
      "category": "Health & Beauty",
      "description": "Hijab-friendly haircuts",
      "location": "East London",
      "contact": "Phone number on website",
      "source": "Instagram TikTok",
      "website": "",
      "instagram": ""
    },
    {
      "id": "13",
      "name": "Sisters Salon",
      "category": "Health & Beauty",
      "description": "Halal haircare hijab-friendly",
      "location": "London",
      "contact": "Instagram DM",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "14",
      "name": "The Cupping Clinic (Female Practitioner)",
      "category": "Health & Beauty",
      "description": "Hijama therapy",
      "location": "London",
      "contact": "WhatsApp number on Instagram",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "15",
      "name": "Sunnah Remedies London",
      "category": "Health & Beauty",
      "description": "Prophetic skincare oils",
      "location": "London",
      "contact": "Etsy messaging",
      "source": "Etsy",
      "website": "",
      "instagram": ""
    },
    {
      "id": "16",
      "name": "Halal Glow Co.",
      "category": "Health & Beauty",
      "description": "Halal skincare vegan serums",
      "location": "London",
      "contact": "Instagram DM",
      "source": "TikTok Shop Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "17",
      "name": "Modest Glow UK",
      "category": "Health & Beauty",
      "description": "Muslim-owned beauty brand",
      "location": "London",
      "contact": "TikTok DM",
      "source": "TikTok",
      "website": "",
      "instagram": ""
    },
    {
      "id": "18",
      "name": "Hijama by Sister Amina",
      "category": "Health & Beauty",
      "description": "Female hijama therapist",
      "location": "West London",
      "contact": "WhatsApp number on Instagram",
      "source": "Instagram",
      "website": "",
      "instagram": ""
    },
    {
      "id": "19",
      "name": "Sunnah Essentials London",
      "category": "Health & Beauty",
      "description": "Prophetic oils skincare",
      "location": "London",
      "contact": "Etsy messaging",
      "source": "Etsy",
      "website": "",
      "instagram": ""
    },
    {
      "id": "20",
      "name": "Noorish London",
      "category": "Health & Beauty",
      "description": "Women-only wellness sanctuary offering hijama facials massage and holistic therapy",
      "location": "London",
      "contact": "Email via website",
      "source": "Noorish London official website",
      "website": "",
      "instagram": ""
    },
    {
      "id": "21",
      "name": "Noshi’s Beauty Hub & Academy",
      "category": "Health & Beauty",
      "description": "Beauty treatments and training academy hijab-friendly salon",
      "location": "London N17",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "22",
      "name": "HALO – The Beauty Retreat",
      "category": "Health & Beauty",
      "description": "Hijab-friendly beauty salon private women-only environment",
      "location": "London N8",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "23",
      "name": "The Beauty Lodge Day Spa",
      "category": "Health & Beauty",
      "description": "Women-only spa offering facials massage and beauty treatments",
      "location": "London N22",
      "contact": "Email/phone via website",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "24",
      "name": "Naz Hair & Beauty Salon",
      "category": "Health & Beauty",
      "description": "Hair beauty threading waxing Muslim-owned",
      "location": "London E17",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "25",
      "name": "Shanze Beauty Parlour",
      "category": "Services",
      "description": "Hair beauty and bridal services Muslim-run",
      "location": "London E17",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "26",
      "name": "Ayesha’s Hair & Beauty",
      "category": "Health & Beauty",
      "description": "Hair beauty waxing facials women-only",
      "location": "Walthamstow London",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "27",
      "name": "Yasemin K Therapies & Beauty",
      "category": "Health & Beauty",
      "description": "Massage facials holistic therapies Muslim-friendly",
      "location": "London E4",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "28",
      "name": "Jennaj Hair & Beauty (Home Salon)",
      "category": "Health & Beauty",
      "description": "Private home-based women-only salon",
      "location": "London",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "29",
      "name": "Beautylicious by Naz (Ilford)",
      "category": "Health & Beauty",
      "description": "Beauty facials waxing hair Muslim-owned",
      "location": "Ilford (Greater London)",
      "contact": "Phone number on listing",
      "source": "MuslimConnect directory",
      "website": "",
      "instagram": ""
    },
    {
      "id": "30",
      "name": "Muslim London Directory (General Source)",
      "category": "Services",
      "description": "Directory listing Muslim-owned beauty and wellbeing services",
      "location": "London",
      "contact": "Website contact",
      "source": "MuslimLondon.com",
      "website": "",
      "instagram": ""
    },
    {
      "id": "31",
      "name": "Hijama Healing London",
      "category": "Health & Beauty",
      "description": "Woman‑only hijama clinic founded by Farida Yasmin; holistic wellness focus",
      "location": "Canary Wharf, London",
      "contact": "Email via website",
      "source": "HijamaHealingLondon.co.uk",
      "website": "",
      "instagram": ""
    },
    {
      "id": "32",
      "name": "London Hijama Clinic (Female Practitioner)",
      "category": "Health & Beauty",
      "description": "Female hijama therapist available at Upton Lane branch",
      "location": "Forest Gate, London",
      "contact": "0208 470 7999",
      "source": "HijamaInLondon.com",
      "website": "",
      "instagram": ""
    },
    {
      "id": "33",
      "name": "Chrisp Street Cupping Clinic (Female Therapist)",
      "category": "Health & Beauty",
      "description": "Clinic offering hijama with female practitioners available",
      "location": "Poplar, London",
      "contact": "07467 029665",
      "source": "ChrispStreetCupping.co.uk",
      "website": "",
      "instagram": ""
    },
    {
      "id": "34",
      "name": "Hijama Sisters London",
      "category": "Services",
      "description": "Women‑only hijama, mobile and clinic‑based services",
      "location": "London (multiple areas)",
      "contact": "WhatsApp via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "35",
      "name": "Healing Hands Hijama (Female Practitioner)",
      "category": "Health & Beauty",
      "description": "Wet cupping, dry cupping, women‑only sessions",
      "location": "East London",
      "contact": "Phone via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "36",
      "name": "Hijama by Sister Zainab",
      "category": "Health & Beauty",
      "description": "Private women‑only hijama therapist",
      "location": "North London",
      "contact": "WhatsApp via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "37",
      "name": "Sunnah Cupping for Sisters",
      "category": "Health & Beauty",
      "description": "Wet cupping for women only; home‑based clinic",
      "location": "South London",
      "contact": "Phone via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "38",
      "name": "Sisters Cupping Therapy London",
      "category": "Health & Beauty",
      "description": "Women‑only hijama, lymphatic detox, back pain therapy",
      "location": "West London",
      "contact": "Phone via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "39",
      "name": "Hijama Care for Women",
      "category": "Health & Beauty",
      "description": "Professional hijama for women only; certified female therapist",
      "location": "East London",
      "contact": "Phone via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "40",
      "name": "Al‑Shifa Hijama for Ladies",
      "category": "Health & Beauty",
      "description": "Wet cupping, migraine therapy, fertility support for women",
      "location": "Ilford / East London",
      "contact": "Phone via listing",
      "source": "Google Business Listing",
      "website": "",
      "instagram": ""
    },
    {
      "id": "41",
      "name": "Husn",
      "category": "Health & Beauty",
      "description": "Minimalist halal-friendly skincare; Muslim-women-owned",
      "location": "Shopify store; strong sales + active community",
      "contact": "",
      "source": "Shopify store; strong sales + active community",
      "website": "",
      "instagram": ""
    },
    {
      "id": "42",
      "name": "Ayuura Beauty",
      "category": "Health & Beauty",
      "description": "Muslimah-owned skincare; gentle, barrier-friendly formulas",
      "location": "Shopify store; high engagement",
      "contact": "",
      "source": "Shopify store; high engagement",
      "website": "",
      "instagram": ""
    },
    {
      "id": "43",
      "name": "Sunnah Glow Co",
      "category": "Health & Beauty",
      "description": "Halal-friendly skincare & body oils",
      "location": "Shopify store; repeat customers",
      "contact": "",
      "source": "Shopify store; repeat customers",
      "website": "",
      "instagram": ""
    },
    {
      "id": "44",
      "name": "Nura Beauty UK",
      "category": "Health & Beauty",
      "description": "Muslim-women-owned skincare; serums & cleansers",
      "location": "Shopify store; UK-based",
      "contact": "",
      "source": "Shopify store; UK-based",
      "website": "",
      "instagram": ""
    },
    {
      "id": "45",
      "name": "Safa Organics",
      "category": "Health & Beauty",
      "description": "Organic body oils & natural skincare",
      "location": "Shopify store; ships worldwide",
      "contact": "",
      "source": "Shopify store; ships worldwide",
      "website": "",
      "instagram": ""
    },
    {
      "id": "46",
      "name": "Afiya Beauty",
      "category": "Health & Beauty",
      "description": "Natural haircare & scalp oils for textured hair",
      "location": "Shopify store; Muslimah-owned",
      "contact": "",
      "source": "Shopify store; Muslimah-owned",
      "website": "",
      "instagram": ""
    },
    {
      "id": "47",
      "name": "Sakeenah Self-Care",
      "category": "Health & Beauty",
      "description": "Wellness brand; candles, oils, bath products",
      "location": "Shopify store; strong sales indicators",
      "contact": "",
      "source": "Shopify store; strong sales indicators",
      "website": "",
      "instagram": ""
    },
    {
      "id": "48",
      "name": "Noor Aromas",
      "category": "Health & Beauty",
      "description": "Aromatherapy, home scents & wellness",
      "location": "Shopify store; UK shipping",
      "contact": "",
      "source": "Shopify store; UK shipping",
      "website": "",
      "instagram": ""
    },
    {
      "id": "49",
      "name": "Hijabi Haircare Co",
      "category": "Health & Beauty",
      "description": "Haircare for hijabi women; scalp care",
      "location": "Shopify store; active restocks",
      "contact": "",
      "source": "Shopify store; active restocks",
      "website": "",
      "instagram": ""
    },
    {
      "id": "50",
      "name": "Sunnah Scents UK",
      "category": "Health & Beauty",
      "description": "Fragrance oils & attars; Muslim-women-owned",
      "location": "Shopify store; repeat buyers",
      "contact": "",
      "source": "Shopify store; repeat buyers",
      "website": "",
      "instagram": ""
    },
    {
      "id": "51",
      "name": "Barakah Botanicals",
      "category": "Health & Beauty",
      "description": "Herbal wellness blends & natural remedies",
      "location": "Shopify store; Muslimah-owned",
      "contact": "",
      "source": "Shopify store; Muslimah-owned",
      "website": "",
      "instagram": ""
    },
    {
      "id": "52",
      "name": "Nourish & Niyyah",
      "category": "Health & Beauty",
      "description": "Self-care brand; candles, bath salts, oils",
      "location": "Shopify store; ships to UK",
      "contact": "",
      "source": "Shopify store; ships to UK",
      "website": "",
      "instagram": ""
    },
    {
      "id": "53",
      "name": "The Modest Glow",
      "category": "Health & Beauty",
      "description": "Skincare for acne-prone & sensitive skin",
      "location": "Shopify store; active social media",
      "contact": "",
      "source": "Shopify store; active social media",
      "website": "",
      "instagram": ""
    },
    {
      "id": "54",
      "name": "Sisters Remedy Co",
      "category": "Health & Beauty",
      "description": "Herbal teas & wellness blends",
      "location": "Shopify store; UK-based",
      "contact": "",
      "source": "Shopify store; UK-based",
      "website": "",
      "instagram": ""
    },
    {
      "id": "55",
      "name": "Halal Glow Cosmetics",
      "category": "Health & Beauty",
      "description": "Halal-friendly makeup & lip products",
      "location": "Shopify store; Muslimah-owned",
      "contact": "",
      "source": "Shopify store; Muslimah-owned",
      "website": "",
      "instagram": ""
    },
    {
      "id": "56",
      "name": "Sunnah Soapery",
      "category": "Health & Beauty",
      "description": "Handmade soaps, body butters, natural skincare",
      "location": "Shopify store; ships worldwide",
      "contact": "",
      "source": "Shopify store; ships worldwide",
      "website": "",
      "instagram": ""
    },
    {
      "id": "57",
      "name": "Niyyah Naturals",
      "category": "Health & Beauty",
      "description": "Organic oils, hair masks, body care",
      "location": "Shopify store; Muslimah-owned",
      "contact": "",
      "source": "Shopify store; Muslimah-owned",
      "website": "",
      "instagram": ""
    },
    {
      "id": "58",
      "name": "Amani Wellness UK",
      "category": "Health & Beauty",
      "description": "Wellness brand; diffusers, oils, aromatherapy",
      "location": "Shopify store; UK shipping",
      "contact": "",
      "source": "Shopify store; UK shipping",
      "website": "",
      "instagram": ""
    },
    {
      "id": "59",
      "name": "Sacred Skin Co",
      "category": "Health & Beauty",
      "description": "Minimalist skincare; Muslim-women-owned",
      "location": "Shopify store; active customer base",
      "contact": "",
      "source": "Shopify store; active customer base",
      "website": "",
      "instagram": ""
    },
    {
      "id": "60",
      "name": "The Hijabi Glow Shop",
      "category": "Health & Beauty",
      "description": "Hijabi-friendly haircare & scalp treatments",
      "location": "Shopify store; ships to London",
      "contact": "",
      "source": "Shopify store; ships to London",
      "website": "",
      "instagram": ""
    },
    {
      "name": "Aab Collection",
      "category": "Fashion & Clothing",
      "description": "Modest fashion abayas jilbabs hijabs; London pop-ups and showroom",
      "location": "London",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/aabcollection",
      "id": "61"
    },
    {
      "name": "Inayah",
      "category": "Fashion & Clothing",
      "description": "Luxury modest womenswear abayas dresses; London showroom",
      "location": "London",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/inayah.london",
      "id": "62"
    },
    {
      "name": "Modest Muse London",
      "category": "Fashion & Clothing",
      "description": "Modest dresses hijabs occasion wear for Muslim women",
      "location": "London",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/modestmuse_london",
      "id": "63"
    },
    {
      "name": "Hijab House London",
      "category": "Fashion & Clothing",
      "description": "Hijabs modest basics for hijabi women",
      "location": "London",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/hijabhouselondon",
      "id": "64"
    },
    {
      "name": "Zahra Apparel",
      "category": "Fashion & Clothing",
      "description": "Handmade modest clothing abayas",
      "location": "London",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/zahraapparel",
      "id": "65"
    },
    {
      "name": "Halal Travel Guide",
      "category": "Travel",
      "description": "Muslim-women-led travel company offering halal-friendly tours & retreats",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/halaltravelguide",
      "id": "66"
    },
    {
      "name": "Muslim Travel Girl",
      "category": "Travel",
      "description": "Muslimah-led travel planning, halal travel tips, London-based",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/muslimtravelgirl",
      "id": "67"
    },
    {
      "name": "Sisters Getaway UK",
      "category": "Travel",
      "description": "Muslim-women-only group trips, retreats & UK adventures",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersgetawayuk",
      "id": "68"
    },
    {
      "name": "Sisters Explore London",
      "category": "Travel",
      "description": "Muslim-women-led London walking tours & cultural experiences",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersexplorelondon",
      "id": "69"
    },
    {
      "name": "Hijabi Explorers UK",
      "category": "Travel",
      "description": "Muslim-women-led adventure & travel group for hijabis",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/hijabiexplorersuk",
      "id": "70"
    },
    {
      "name": "Muslimah Adventures UK",
      "category": "Travel",
      "description": "Women-only travel & adventure experiences for Muslim women",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/muslimahadventuresuk",
      "id": "71"
    },
    {
      "name": "Sisters Travel Circle",
      "category": "Travel",
      "description": "Muslim-women-led travel community offering group trips",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sisterstravelcircle",
      "id": "72"
    },
    {
      "name": "Halal Getaways UK",
      "category": "Travel",
      "description": "Muslimah-owned halal-friendly UK staycation planning",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/halalgetawaysuk",
      "id": "73"
    },
    {
      "name": "Sisters Retreats London",
      "category": "Travel",
      "description": "Muslim-women-led wellness & travel retreats",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersretreatslondon",
      "id": "74"
    },
    {
      "name": "The Modest Traveller",
      "category": "Travel",
      "description": "Muslimah travel blogger offering curated London experiences",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/themodesttraveller",
      "id": "75"
    },
    {
      "name": "Sisters Day Out London",
      "category": "Travel",
      "description": "Muslim-women-led London day trips & cultural tours",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersdayoutlondon",
      "id": "76"
    },
    {
      "name": "Hijabi Travel Club",
      "category": "Travel",
      "description": "Muslim-women-only travel meetups & group trips",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/hijabitravelclub",
      "id": "77"
    },
    {
      "name": "Sisters Walking Tours London",
      "category": "Travel",
      "description": "Women-only guided walking tours led by Muslim women",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sisterswalkslondon",
      "id": "78"
    },
    {
      "name": "Muslimah Solo Travel UK",
      "category": "Travel",
      "description": "Solo travel support & London meetups for Muslim women",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/muslimahsolotraveluk",
      "id": "79"
    },
    {
      "name": "Sisters Adventure Club",
      "category": "Travel",
      "description": "Muslim-women-led outdoor activities & UK travel days",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersadventureclub",
      "id": "80"
    },
    {
      "name": "@HalalLondonExplorer",
      "category": "Travel",
      "description": "Muslimah-led London tourism tips & halal travel guides",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/HalalLondonExplorer",
      "id": "81"
    },
    {
      "name": "Sisters Culture Walks",
      "category": "Travel",
      "description": "Muslim-women-led cultural & historical walking tours",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sistersculturewalks",
      "id": "82"
    },
    {
      "name": "Muslimah Heritage Tours",
      "category": "Travel",
      "description": "Women-only Islamic history tours in London",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/muslimahtours",
      "id": "83"
    },
    {
      "name": "Sisters City Breaks UK",
      "category": "Travel",
      "description": "Muslim-women-led UK city trips & group travel",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sisterscitybreaksuk",
      "id": "84"
    },
    {
      "name": "Sisters Travel Concierge",
      "category": "Travel",
      "description": "Muslimah-led bespoke travel planning & itinerary services",
      "location": "Online",
      "contact": "",
      "source": "Excel Import",
      "website": "",
      "instagram": "https://www.instagram.com/sisterstravelconcierge",
      "id": "85"
    },
    {
      "name": "Bethnal Green Spa Experience",
      "category": "Health & Beauty",
      "description": "Spa offering women-only days and Turkish hammam experience",
      "location": "Bethnal Green, London",
      "source": "Muslim Connect",
      "contact": "See website for women-only schedule",
      "id": "86"
    },
    {
      "name": "The Organic Pharmacy Spa",
      "category": "Health & Beauty",
      "description": "All-natural, alcohol-free products with private treatment rooms available",
      "location": "Chelsea, London",
      "source": "Muslim Connect",
      "contact": "Phone booking required for private rooms",
      "id": "87"
    },
    {
      "name": "Jazz Panesar",
      "category": "Health & Beauty",
      "description": "Asian bridal hair and makeup artist catering to modern and traditional styles",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Contact via website/socials",
      "id": "88"
    },
    {
      "name": "Kajol R Paswwan",
      "category": "Health & Beauty",
      "description": "Specialized bridal makeup services and professional training",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Contact via website",
      "id": "89"
    },
    {
      "name": "Albay Bakery",
      "category": "Food & Drinks",
      "description": "Muslim-friendly bakery offering halal pastries and breads",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit store",
      "id": "90"
    },
    {
      "name": "Doga Patisserie",
      "category": "Food & Drinks",
      "description": "Halal-compliant patisserie serving cakes and desserts",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit store",
      "id": "91"
    },
    {
      "name": "Yasar Halim Patisserie",
      "category": "Food & Drinks",
      "description": "High-quality halal desserts and baked goods",
      "location": "Harringay, London",
      "source": "Muslim Connect",
      "contact": "Visit store",
      "id": "92"
    },
    {
      "name": "Prestige Patisserie",
      "category": "Food & Drinks",
      "description": "Halal-compliant baked goods and artisan desserts",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit store",
      "id": "93"
    },
    {
      "name": "Cake Box Tottenham",
      "category": "Food & Drinks",
      "description": "Egg-free and halal-compliant fresh cream cakes",
      "location": "Tottenham, London",
      "source": "Muslim Connect",
      "contact": "Visit store",
      "id": "94"
    },
    {
      "name": "Flame ‘Inn’ Karahi",
      "category": "Food & Drinks",
      "description": "Authentic halal Indian cuisine in a family-friendly setting",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "95"
    },
    {
      "name": "Hajee Talib Fish & Chips",
      "category": "Food & Drinks",
      "description": "Traditional fish and chips cooked to halal standards",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "96"
    },
    {
      "name": "Sammy’s Chicken n Shakes",
      "category": "Food & Drinks",
      "description": "Halal comfort food, chicken and shakes",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "97"
    },
    {
      "name": "98 Sizzle",
      "category": "Food & Drinks",
      "description": "Casual dining serving high-quality halal sizzler dishes",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "98"
    },
    {
      "name": "Toronto Crispy",
      "category": "Food & Drinks",
      "description": "Halal fried chicken and fast food",
      "location": "London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "99"
    },
    {
      "name": "Nordens Chartered Accountants",
      "category": "Services",
      "description": "Trusted accounting and financial services",
      "location": "Redbridge, London",
      "source": "Muslim Connect",
      "contact": "Contact via website",
      "id": "100"
    },
    {
      "name": "Remote Accounting Ltd",
      "category": "Services",
      "description": "Finance and accounting services for businesses and individuals",
      "location": "Redbridge, London",
      "source": "Muslim Connect",
      "contact": "Contact via website",
      "id": "101"
    },
    {
      "name": "Ummah Catering",
      "category": "Services",
      "description": "Halal catering service specializing in high-quality food and event decorations",
      "location": "Walthamstow, London",
      "source": "Muslim Connect",
      "contact": "Visit Unit 30, Walthamstow Business Centre",
      "id": "102"
    },
    {
      "name": "Zam Zam Halal Meat & Poultry",
      "category": "Shopping",
      "description": "Premier halal meat shop offering fresh poultry and meat",
      "location": "Newham, London",
      "source": "Muslim Connect",
      "contact": "Visit 855 Romford Rd",
      "id": "103"
    },
    {
      "name": "Nimat Halal Meat",
      "category": "Shopping",
      "description": "Trusted local halal meat provider",
      "location": "Newham, London",
      "source": "Muslim Connect",
      "contact": "Visit 29 Barking Rd",
      "id": "104"
    },
    {
      "name": "Online Meat Shop",
      "category": "Shopping",
      "description": "High-quality halal meat provider with online services",
      "location": "Newham, London",
      "source": "Muslim Connect",
      "contact": "Visit 328 High Street North",
      "id": "105"
    },
    {
      "name": "Leyton Leisure Lagoon",
      "category": "Health & Beauty",
      "description": "Hosts weekly 'Sisters Swim' sessions for women only",
      "location": "Waltham Forest, London",
      "source": "Muslim Connect",
      "contact": "Check schedule for Sisters Swim",
      "id": "106"
    },
    {
      "name": "Camberwell Leisure Centre",
      "category": "Health & Beauty",
      "description": "Offers swimming pool sessions closed to all but women",
      "location": "Southwark, London",
      "source": "Muslim Connect",
      "contact": "Check schedule for women-only sessions",
      "id": "107"
    },
    {
      "name": "Clissold Leisure Centre",
      "category": "Health & Beauty",
      "description": "Faith and culturally sensitive swimming lessons for children and women",
      "location": "Hackney, London",
      "source": "Muslim Connect",
      "contact": "Inquire about culturally sensitive lessons",
      "id": "108"
    },
    {
      "name": "Oasis Sports Centre",
      "category": "Health & Beauty",
      "description": "Provides modest family swimming sessions",
      "location": "Camden, London",
      "source": "Muslim Connect",
      "contact": "Check family swim schedule",
      "id": "109"
    },
    {
      "name": "Aspire Centre",
      "category": "Health & Beauty",
      "description": "Swim groups specifically for community-led Muslim women",
      "location": "Southfields, London",
      "source": "Muslim Connect",
      "contact": "Inquire about Muslim women groups",
      "id": "110"
    },
    {
      "name": "Berenjak London",
      "category": "Food & Drinks",
      "description": "Authentic Persian cuisine with halal options",
      "location": "Soho, London",
      "source": "Muslim Connect",
      "contact": "Visit restaurant",
      "id": "111"
    },
    {
      "name": "Sabirah",
      "category": "Fashion & Clothing",
      "description": "Luxury occasion-wear and sustainable modest fashion. Founded by Deborah Latouche.",
      "location": "London",
      "contact": "Via website",
      "website": "https://www.sabihah.london",
      "instagram": "https://www.instagram.com/sabirah_collection",
      "id": "mkx2y6nks8qwp"
    },
    {
      "name": "Saeedah Haque",
      "category": "Fashion & Clothing",
      "description": "Streetwear abayas bridging Islamic tradition and modern utility. First abaya collaboration with Nike.",
      "location": "North London",
      "contact": "Via website",
      "website": "https://www.saeedahhaque.com",
      "instagram": "https://www.instagram.com/saeedahhaque",
      "id": "mkx2y6nku5q8m"
    },
    {
      "name": "Sabihah London",
      "category": "Fashion & Clothing",
      "description": "Modest ready-to-wear clothing inspired by vintage and contemporary fashion.",
      "location": "London",
      "contact": "Via website",
      "website": "https://www.sabihah.london",
      "instagram": "",
      "id": "mkx2y6ns8ezaw"
    },
    {
      "name": "The Great Chase",
      "category": "Food & Drinks",
      "description": "Fine dining halal restaurant with a dry bar and dedicated prayer room.",
      "location": "Islington, London",
      "contact": "Book via website",
      "website": "https://www.thegreatchase.co.uk",
      "instagram": "https://www.instagram.com/thegreatchase",
      "id": "mkx2y6ns12jp4"
    },
    {
      "name": "Etles Uyghur Restaurant",
      "category": "Food & Drinks",
      "description": "Authentic Uyghur cuisine from Xinjiang. Family-run and highly rated.",
      "location": "Walthamstow & Finchley",
      "contact": "020 3620 6978",
      "website": "https://etles.co.uk",
      "instagram": "https://www.instagram.com/etles.restaurant",
      "id": "mkx2y6nsxz0oh"
    },
    {
      "name": "Panadera Bakery",
      "category": "Food & Drinks",
      "description": "Filipino bakery offering halal options, famous for sandos and pastries.",
      "location": "Kentish Town, London",
      "contact": "Via website",
      "website": "https://www.panadera.co.uk",
      "instagram": "https://www.instagram.com/panaderabakery_",
      "id": "mkx2y6ns0xsws"
    },
    {
      "name": "Aveda Covent Garden (Privacy Suite)",
      "category": "Health & Beauty",
      "description": "Flagship salon offering a private 'Privacy Suite' specifically for guests who cover their hair.",
      "location": "Covent Garden, London",
      "contact": "020 7759 7355",
      "website": "https://www.aveda.co.uk",
      "instagram": "",
      "id": "mkx2y6ns6n48a"
    },
    {
      "name": "Maryam Hair and Beauty",
      "category": "Health & Beauty",
      "description": "Ladies-only salon providing a safe and comfortable environment for Muslim women.",
      "location": "London",
      "contact": "Via website",
      "website": "https://maryamhairandbeauty.co.uk",
      "instagram": "",
      "id": "mkx2y6nsinrgo"
    },
    {
      "name": "Muslim Women's Network UK",
      "category": "Community & Education",
      "description": "National charity campaigning for the rights of Muslim women and girls.",
      "location": "London / National",
      "contact": "Via website",
      "website": "https://www.mwnuk.co.uk",
      "instagram": "https://www.instagram.com/mwnuk",
      "id": "mkx2y6nt48750"
    },
    {
      "name": "Muslim Women Connect",
      "category": "Community & Education",
      "description": "Mentoring and networking organization connecting Muslim women across professional sectors.",
      "location": "London",
      "contact": "Via website",
      "website": "https://muslimwomenconnect.com",
      "instagram": "https://www.instagram.com/muslimwomenconnect",
      "id": "mkx2y6ntoamtb"
    },
    {
      "name": "Sisters Swim - Leyton",
      "category": "Community & Education",
      "description": "Women-only swimming sessions at Leyton Leisure Lagoon.",
      "location": "Leyton, London",
      "contact": "Check leisure centre schedule",
      "website": "https://www.better.org.uk",
      "instagram": "",
      "id": "mkx2y6ntqw4y5"
    }
  ]
};